### ISSUE TITLE
Bring over Build Pipeline

### ISSUE THREAD

**Issue by gfs** [microsoft/RecursiveExtractor#1]

**Comment by gat786** [comment]
Does this issue mean to write a build pipeline for this project?

**Comment by gfs** [comment]
Yes. This project was originally a component of Microsoft/OSSGadget and has a build pipeline written. Just needs to be reconfigured with the new repo.

**Comment by gat786** [comment]
so i checked the template from Microsoft/OSSGadget and found that some templates that were mentioned in the `recursiveextractor-pipeline.yml` are not in this repo. Like 

- dotnet-publish-linux-mac-job.yml

- dotnet-publish-win-netcore-job.yml

- dotnet-test-job.yml

- nbgv-set-version-steps.yml

- nuget-build-job.yml

- sdl-job.yml

are not in this repo. do we want to ignore all together whatever these pipelines used to do?

**Comment by gfs** [comment]
Those will need to be copied over.

@daalcant will be completing this once we get the signing key ready and can publish signed releases from this repo.

**Comment by gat786** [comment]
aight so nothing to do here right now cheers!

**Comment by gfs** [comment]
Thanks for your interest and let me know if you have any other questions.

We should have this closed in a couple of days.

**Comment by gat786** [comment]
I am just looking to get started with contribution to opensource and was looking towards repos and found this. It might be helpful if you can point me to a nice direction for that 👍

**Comment by gfs** [comment]
That's awesome, and we definitely encourage contributions.

I manage a couple of other projects:
https://github.com/microsoft/OAT
https://github.com/microsoft/Devskim
https://github.com/microsoft/AttackSurfaceAnalyzer

My team also manages:
https://github.com/microsoft/ApplicationInspector

For a specific issue that you might be able to jump into I think https://github.com/microsoft/DevSkim/issues/116 is a good candidate.  If you're interested comment there and I'll gather more context for you on what needs to be done.

**Comment by gat786** [comment]
lemme have a look at the issue and see if i will be able to pull it of and will get to you if it seems like it :) thanks btw....!

**Comment by gfs** [comment]
Another one, if you specifically wanted to do something with GitHub Actions this won't be too hard, just publish to your own fork.

https://github.com/microsoft/DevSkim/issues/211

**Comment by gat786** [comment]
I can do that thanks ;)
