### ISSUE TITLE
RAR archives extracted in parallel fails

### ISSUE THREAD

**Issue by svenclaesson** [microsoft/RecursiveExtractor#102]
Extracting RAR packages **when Parallel = true** results in several failed files
Example [here](http://samples.ffmpeg.org/drivers32/qnap.rar) (rar4). This file works fine when Parallel = false.

**Comment by gfs** [comment]
Thanks for the report and the report file.

**Comment by gfs** [comment]
I can reproduce this. The tests have validated that the number of files extracted is correct, but it does appear that parallel extraction of RARs is resulting in incomplete files.

I looekd over our implementation and don't notice anything obviously wrong with the parallel implementation that would cause such an issue - so my suspicion is that the SharpCompress dependency's RarArchive implementation is not threadsafe. Taking a quick look at the code, we call OpenEntryStream, which calls the RarStream ctor, which then directly reads off the Archive's Stream, and does not appear to account for locking/thread safety. I suspect it is the side effects of moving the stream pointers that may be causing this behavior.

I am working on a PR to simply remove the parallelized implementation from the RarExtractor in RecursiveExtractor now.

**Comment by svenclaesson** [comment]
Thank you very much for your quick response and working on the fix!
