### ISSUE TITLE
Extract swallows timeout exception

### ISSUE THREAD

**Issue by svenclaesson** [microsoft/RecursiveExtractor#107]
Because of an [issue in SharpCompress](https://github.com/adamhathcock/sharpcompress/issues/710) with very slow 7zip extraction it's easy to get in a situation where it takes many hours to extract a few thousand small files.

Because of this I've enabled timeout
`new ExtractorOptions() { Timeout = TimeSpan.FromMinutes(10), EnableTiming = true, }`

When trying this I found that this exception is swallowed in Extractor.Extract(...) and only a fraction of the files are returned.
Extractor.ExtractAsync(...) does not catch this exception and leaves it to the caller. Here it works as expected.

**Comment by gfs** [comment]
Do you have an example file you can share for this? This might be fixed as a side effect of #101 this switched from a try which populates a list to a true enumeration which shouldn't swallow exceptions.

**Comment by gfs** [comment]
I found the sample in the linked thread. The timeout appears to work in #101 with the provided file.
