### ISSUE TITLE
Migrate to LTRData/DiscUtils

### ISSUE THREAD

**Issue by gfs** [microsoft/RecursiveExtractor#144]
Per report in #93 LTRData now publishes a nuget of their fork of diskutils (https://www.nuget.org/packages/LTRData.DiscUtils.Core). We should try to migrate to this fork as it is more actively maintained.

**Comment by gfs** [comment]
Quick test indicates relatively simple to change the dependencies, but there are a number of test regressions particularly with wim files that appear to require some refactoring of the WIM extractor.

**Comment by gfs** [comment]
Exception gets thrown on line 467 of WimFileSystem when attempting to enumerate all files in the WIM during tests. Will probably need to take a look at what has changed here from the base DiscUtils package to figure out what is going wrong.

![Image](https://github.com/microsoft/RecursiveExtractor/assets/98900/c67f7f8e-726f-4c05-96ca-11ad94c6daac)

**Comment by Erik-White** [comment]
I have opened a PR in LTRData/DiscUtils to fix their WIM support: https://github.com/LTRData/DiscUtils/pull/3
It should be nice and easy once that is sorted

**Comment by Erik-White** [comment]
After a quick test, it seems that #59 would also be closed by switching to the LTRData fork, a nice bonus!

I have started a PR to help keep track https://github.com/microsoft/RecursiveExtractor/pull/145

**Comment by gfs** [comment]
Awesome! Thanks for digging into this @Erik-White!
