### ISSUE TITLE
RecursiveExtractor fails for some archives (fail to create file)

### ISSUE THREAD

**Issue by scovetta** [microsoft/RecursiveExtractor#28]
Repro:
1. Download https://github.com/microsoft/OSSGadget/releases/download/v0.1.237/OSSGadget_linux_0.1.237.zip.
2. Run the RecursiveExtractor CLI against that zip file.

The output contains contain something like:

```
Extracted OSSGadget_linux_0.1.237.zip\OSSGadget_linux_0.1.237\System.Security.Cryptography.Native.OpenSsl.a\openssl.c.o.
Extracted OSSGadget_linux_0.1.237.zip\OSSGadget_linux_0.1.237\System.Security.Cryptography.Native.OpenSsl.a\apibridge.c.o.

2020-09-06 21:14:02.3523|FATAL|Microsoft.CST.RecursiveExtractor.Extractor|Failed to create file at bb\OSSGadget_linux_0.1.237.zip\OSSGadget_linux_0.1.237\System.Security.Cryptography.Native.OpenSsl.a\.

Extracted OSSGadget_linux_0.1.237.zip\OSSGadget_linux_0.1.237\System.Security.Cryptography.Native.OpenSsl.so.
Extracted OSSGadget_linux_0.1.237.zip\OSSGadget_linux_0.1.237\System.Security.Cryptography.OpenSsl.dll.
Extracted OSSGadget_linux_0.1.237.zip\OSSGadget_linux_0.1.237\System.Security.Cryptography.Pkcs.dll.
```

I believe this is happening in [Extractor.ExtractToDirectory](https://github.com/microsoft/RecursiveExtractor/blob/main/RecursiveExtractor/Extractor.cs#L496) since `targetPath` is a directory that already exists.

**Comment by gfs** [comment]
I am seeing some weird behavior with this file.  Will investigate.

**Comment by gfs** [comment]
I see what is happening here now.  This zip file contains actual zipped items named `.`. We can't extract those because `.`already exists on linux.  Whatever zipped them shouldn't be including the `.`.

I think this warning is correct.  I can load this zip in the GUI and unzip it using the command line with only those warnings which I think are okay to show.
