### ISSUE TITLE
Replace test files with "lorem ipsum"

### ISSUE THREAD

**Issue by scovetta** [microsoft/RecursiveExtractor#37]
Some of the test files contain text from OSS Gadget files, including some fragments containing 'MD5':

https://github.com/microsoft/RecursiveExtractor/search?q=md5

While this isn't a security risk, it'll show up in automated scans, so we should switch out those files for "Lorem Ipsum" type text, since the content doesn't matter.

**Comment by gfs** [comment]
Fixed by #44
