### ISSUE TITLE
Provide an option to use provided file extensions instead of checking bytes

### ISSUE THREAD

**Issue by guyacosta** [microsoft/RecursiveExtractor#42]
Microsoft office files with .docx, .xlsx, and perhaps others are identifed as archive file types i.e. MiniMagic.DetectFileType returns a type ZIP for them.  Now, they technically appear to be that i.e. you can unzip them apparently and they contain other files like xml docs etc. but for practical purposes they may not be the desired result i.e. the user is unlikely to expect them to be unzipped but treated like a single document.  It can lead to unexpected results and lost processing time.

Request: assess if the file type is a known document type earlier in the detection process which is accepted as a non archive type unless a new override flag is provided to ignore file extensions so similar effect.

**Comment by gfs** [comment]
If you provide a list of extensions to ignore I can add an optional argument that will change the behavior to look at the file extension against a list of known ones.

**Comment by gfs** [comment]
Updated: This should be a new option to provide a list of file extensions to trust are "not" archives.
