### ISSUE TITLE
Extraction of files leading with numbers n. is removed while extracting ar-archives

### ISSUE THREAD

**Issue by Lieth** [microsoft/RecursiveExtractor#71]
We have a test archive of type test.ar which contains three files 1.lorem.txt, 2.lorem.txt and 3.lorem.txt. If we unpack these by recursive extractor each entry contains the same filename. It seems the 1., 2. and 3. is removed for some reason.

So each entry is returned with the name lorem.txt which gives a collision on extracting the entries. The fullpath is also the same \Lorem.txt or in the example below "\\test.ar\\Lorem.txt"

Archice is included within the zipfile since ar-files aren't allowed to be added directly.

[Test.zip](https://github.com/microsoft/RecursiveExtractor/files/7702859/Test.zip)

```
using var stream = new FileStream("Test.zip", FileMode.Open);
var entries = new Extractor().Extract(string.Empty, stream, options).ToList()
```

**Comment by gfs** [comment]
Thanks for your report and the example file.

This hopefully will be an easy fix.

**Comment by gfs** [comment]
I've examined the file you provided and the file names recorded in the ar file are in fact all "Lorem.txt". 

You can see this by opening the ar file in a text editor (ar files are just concatenations of the raw bytes of the files with headers for the length and file name. 

You can see in the attached image I've highlighted two of the headers in the ar file you provided and both name the file simply "Lorem.txt".

![image](https://user-images.githubusercontent.com/98900/146555336-70e0ed81-6866-4eef-affc-ad77435742f8.png)
