### ISSUE TITLE
Wrong numbers of entries in TAR archive

### ISSUE THREAD

**Issue by Lieth** [microsoft/RecursiveExtractor#72]
I created a TAR archive using 7-zip and then proceeded to extract this archive using this project. I both tried to extract the archive given the method using the filepath and the method where I pass a stream of the file, both gives the same error.

Steps to recreate this
- Create a TAR archive using 7-zip (others might work too) containing two or three files
- Run a test with the following code:
```
using var stream = new FileStream(path, FileMode.Open);
var entries = new Extractor().Extract(string.Empty, stream).ToList();
```
or
`var entries = new Extractor().Extract(path).ToList();`

- Verify the number of entries against the number of files added to the TAR archive
- The number of entries in the archive is one less than the number of files added to the archive

**Comment by gfs** [comment]
Can you provide a tar archive that reproduces this problem?

Is it always the same file that is missing?

Is there anything special about the missing file?

**Comment by gfs** [comment]
Cannot reproduce this. I created a tar archive with 5 files with 7z and was able to properly extract all 5 files running the CLI from visual studio.

**Comment by Lieth** [comment]
File added which contains two entries. Since we aren't allowed to upload tar files to github I added extension .zip but remove that and get back the tar file.

With this file I get 1 entry instead of 2.

Using the NUnit test below that fails
```
[Test]
public void Extract_Tar_Archive_Gives_Correct_Number_Of_Entries()
{
  var filePath = @"C:\Users\jimmy\Downloads\Single\ExampleFaultyNumberOfEntries.tar";
  var entries = new Extractor().Extract(filePath).ToList();
  entries.Should().HaveCount(2);
}
```

[ExampleFaultyNumberOfEntries.tar.zip](https://github.com/microsoft/RecursiveExtractor/files/7852817/ExampleFaultyNumberOfEntries.tar.zip)

**Comment by Lieth** [comment]
And as an answer to the question, we have been able to create tar archives both with 7-zip and directly from commandprompt in linux and all files gives wrong number of entries. 

I haven't examined which fileentry that is missing but it doesn't seem to be some special type of file at least. There have been png file, pdf file and other types.

**Comment by gfs** [comment]
Thanks for the additional info and the test file. I'll take a look today.

**Comment by gfs** [comment]
I can reproduce this.  I believe I have a fix mostly done.  The issue appears to be opening streams for the tar entries and then not disposing them before opening another one.

**Comment by gfs** [comment]
Hope to merge a fix this week. I first need to double check this issue isn't present in some of the other extractors.

**Comment by Lieth** [comment]
Amazing work, I will update our use and try it out next week.

Best regards
Jimmy
________________________________

**Comment by gfs** [comment]
Thanks again for the report. Let me know if you run into any additional issues.
